  name: Check Tested Up to Version
  on:
   schedule:
    - cron: '0 0 * * *' # Daily
  jobs:
    check-if-outdated:
      name: Check "Tested up to" Version
      outputs:
        needs-testing: ${{ steps.setup-outputs.outputs.needs-testing }}
        version: ${{ steps.setup-outputs.outputs.version }}
        changelog: ${{ steps.setup-outputs.outputs.changelog }}
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Setup Outputs
        id: setup-outputs
        run: |
         echo ::set-output name=needs-testing::$(php ./bin/check-tested-up-to.php woocommerce)
         echo ::set-output name=version::$(php ./bin/check-tested-up-to.php woocommerce version)
         echo ::set-output name=changelog::$(php ./bin/check-tested-up-to.php woocommerce changelog)
    create-issue:
      name: Create/Update issue
      if: ${{needs.check-if-outdated.outputs.needs-testing == 'true' }}
      permissions:
        contents: read
        issues: write 
      needs: check-if-outdated
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: dblock/create-a-github-issue@v3
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            LATEST_VERSION: ${{needs.check-if-outdated.outputs.version}}
            CHANGELOG: ${{needs.check-if-outdated.outputs.changelog}}
            NAME: WooCommerce
          with:
            filename: .github/ISSUE_TEMPLATE/Test_WooCommerce.md
            update_existing: true
            search_existing: all
        